name: outback
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - ipykernel
  - selenium
  - python-chromedriver-binary 
  - beautifulsoup4
  - pandas
  - sqlalchemy
  - matplotlib
  - sklearn
